package com.example.getfileResource;
import org.apache.commons.lang.StringEscapeUtils;
public class TestUnicode {
    public static void main(String[] args) {

        /*System.out.println("en: "+StringEscapeUtils.escapeJava("Continue"));
        System.out.println("da: "+StringEscapeUtils.escapeJava("Fortsæt"));
        System.out.println("fi: "+StringEscapeUtils.escapeJava("Jatka"));
        System.out.println("fr: "+StringEscapeUtils.escapeJava("Continuer"));
        System.out.println("de: "+StringEscapeUtils.escapeJava("Weiter"));
        System.out.println("el: "+StringEscapeUtils.escapeJava("Συνέχεια"));
        System.out.println("hu: "+StringEscapeUtils.escapeJava("Folytatás"));
        System.out.println("it: "+StringEscapeUtils.escapeJava("Continua"));
        System.out.println("ja: "+StringEscapeUtils.escapeJava("続行"));
        System.out.println("pl: "+StringEscapeUtils.escapeJava("Dalej"));
        System.out.println("pt: "+StringEscapeUtils.escapeJava("Continuar"));
        //System.out.println("pt_BR: "+StringEscapeUtils.escapeJava("Continuar"));
        System.out.println("ro: "+StringEscapeUtils.escapeJava("Continuare"));
        System.out.println("ru: "+StringEscapeUtils.escapeJava("Продолжить"));
        System.out.println("es: "+StringEscapeUtils.escapeJava("Continuar"));
        System.out.println("sv: "+StringEscapeUtils.escapeJava("Fortsätt"));
        System.out.println("fr-CA: "+StringEscapeUtils.escapeJava("Continuer"));
        System.out.println("en_CA: "+StringEscapeUtils.escapeJava("Continue"));
        System.out.println("es-MX: "+StringEscapeUtils.escapeJava("Continuar"));
        System.out.println("en-US: "+StringEscapeUtils.escapeJava("Continue"));
        System.out.println("en-PA: "+StringEscapeUtils.escapeJava("Continue"));
        System.out.println("no: "+StringEscapeUtils.escapeJava("Fortsett"));
        System.out.println("zh-CN: "+StringEscapeUtils.escapeJava("继续"));
        System.out.println("nl: "+StringEscapeUtils.escapeJava("Doorgaan"));
        System.out.println("nn-NO: "+StringEscapeUtils.escapeJava("Fortsett"));
        System.out.println("nb-NO: "+StringEscapeUtils.escapeJava("Fortsett"));
        System.out.println("cs: "+StringEscapeUtils.escapeJava("Pokračovat"));
        System.out.println("bg: "+StringEscapeUtils.escapeJava("Напред"));
        System.out.println("en_NZ: "+StringEscapeUtils.escapeJava("Continue"));
        System.out.println("nl_BE: "+StringEscapeUtils.escapeJava("Doorgaan"));
        System.out.println("de_BE: "+StringEscapeUtils.escapeJava("Weiter"));
        System.out.println("fr_BE: "+StringEscapeUtils.escapeJava("Continuer"));
       // System.out.println("pl_PL: "+StringEscapeUtils.escapeJava("Dalej"));*/
        /*System.out.println("en: "+StringEscapeUtils.escapeJava("Reload"));
        System.out.println("da: "+StringEscapeUtils.escapeJava("Genindlæs"));
        System.out.println("fi: "+StringEscapeUtils.escapeJava("Lataa uudelleen"));
        System.out.println("fr: "+StringEscapeUtils.escapeJava("Recharger"));
        System.out.println("de: "+StringEscapeUtils.escapeJava("Neu laden"));
        System.out.println("el: "+StringEscapeUtils.escapeJava("Επαναφόρτωση"));
        System.out.println("hu: "+StringEscapeUtils.escapeJava("Újratöltés"));
        System.out.println("it: "+StringEscapeUtils.escapeJava("Ricarica"));
        System.out.println("ja: "+StringEscapeUtils.escapeJava("再ロード"));
        System.out.println("pl: "+StringEscapeUtils.escapeJava("Załaduj ponownie"));
        System.out.println("pt: "+StringEscapeUtils.escapeJava("Recarregar"));
        //System.out.println("pt_BR: "+StringEscapeUtils.escapeJava("Recarregar"));
        System.out.println("ro: "+StringEscapeUtils.escapeJava("Reîncărcare"));
        System.out.println("ru: "+StringEscapeUtils.escapeJava("Перезагрузить"));
        System.out.println("es: "+StringEscapeUtils.escapeJava("Volver a cargar"));
        System.out.println("sv: "+StringEscapeUtils.escapeJava("Starta om"));
        System.out.println("fr-CA: "+StringEscapeUtils.escapeJava("Actualiser"));
        System.out.println("en_CA: "+StringEscapeUtils.escapeJava("Reload"));
        System.out.println("es-MX: "+StringEscapeUtils.escapeJava("Recargar"));
        System.out.println("en-US: "+StringEscapeUtils.escapeJava("Reload"));
        System.out.println("en-PA: "+StringEscapeUtils.escapeJava("Reload"));
        System.out.println("no: "+StringEscapeUtils.escapeJava("Last inn på nytt"));
        System.out.println("zh-CN: "+StringEscapeUtils.escapeJava("重新加载"));
        System.out.println("nl: "+StringEscapeUtils.escapeJava("Opnieuw laden"));
        System.out.println("nn-NO: "+StringEscapeUtils.escapeJava("Last inn på nytt"));
        System.out.println("nb-NO: "+StringEscapeUtils.escapeJava("Last inn på nytt"));
        System.out.println("cs: "+StringEscapeUtils.escapeJava("Obnovit"));
        System.out.println("bg: "+StringEscapeUtils.escapeJava("Презареждане"));
        System.out.println("en_NZ: "+StringEscapeUtils.escapeJava("Reload"));
        System.out.println("nl_BE: "+StringEscapeUtils.escapeJava("Opnieuw laden"));
        System.out.println("de_BE: "+StringEscapeUtils.escapeJava("Neu laden"));
        System.out.println("fr_BE: "+StringEscapeUtils.escapeJava("Recharger"));
        // System.out.println("pl_PL: "+StringEscapeUtils.escapeJava("Załaduj ponownie"));*/
        System.out.println("en: "+StringEscapeUtils.escapeJava("View Account History"));
        System.out.println("da: "+StringEscapeUtils.escapeJava("Vis kontohistorik"));
        System.out.println("fi: "+StringEscapeUtils.escapeJava("Näytä tilihistoria"));
        System.out.println("fr: "+StringEscapeUtils.escapeJava("Voir l'historique du compte"));
        System.out.println("de: "+StringEscapeUtils.escapeJava("Kontoverlauf anzeigen"));
        System.out.println("el: "+StringEscapeUtils.escapeJava("Προβολή ιστορικού λογαριασμού"));
        System.out.println("hu: "+StringEscapeUtils.escapeJava("Fiók-előzmények megtekintése"));
        System.out.println("it: "+StringEscapeUtils.escapeJava("Visualizza la cronologia del conto"));
        System.out.println("ja: "+StringEscapeUtils.escapeJava("アカウント履歴を表示する"));
        System.out.println("pl: "+StringEscapeUtils.escapeJava("Wyświetl historię konta"));
        System.out.println("pt: "+StringEscapeUtils.escapeJava("Visualizar histórico da conta"));
        //System.out.println("pt_BR: "+StringEscapeUtils.escapeJava("Ver histórico da conta"));
        System.out.println("ro: "+StringEscapeUtils.escapeJava("Vizualizare istoric cont"));
        System.out.println("ru: "+StringEscapeUtils.escapeJava("Просмотр истории счета"));
        System.out.println("es: "+StringEscapeUtils.escapeJava("Ver historial de la cuenta"));
        System.out.println("sv: "+StringEscapeUtils.escapeJava("Visa kontohistorik"));
        System.out.println("fr-CA: "+StringEscapeUtils.escapeJava("Afficher l'historique du compte"));
        System.out.println("en_CA: "+StringEscapeUtils.escapeJava("View Account History"));
        System.out.println("es-MX: "+StringEscapeUtils.escapeJava("Ver historial de cuenta"));
        System.out.println("en-US: "+StringEscapeUtils.escapeJava("View Account History"));
        System.out.println("en-PA: "+StringEscapeUtils.escapeJava("View Account History"));
        System.out.println("no: "+StringEscapeUtils.escapeJava("Se kontohistorikk"));
        System.out.println("zh-CN: "+StringEscapeUtils.escapeJava("查看账户历史记录"));
        System.out.println("nl: "+StringEscapeUtils.escapeJava("Accountgeschiedenis weergeven"));
        System.out.println("nn-NO: "+StringEscapeUtils.escapeJava("Se kontohistorikk"));
        System.out.println("nb-NO: "+StringEscapeUtils.escapeJava("Se kontohistorikk"));
        System.out.println("cs: "+StringEscapeUtils.escapeJava("Zobrazit historii účtu"));
        System.out.println("bg: "+StringEscapeUtils.escapeJava("Преглед на историята на профила"));
        System.out.println("en_NZ: "+StringEscapeUtils.escapeJava("View Account History"));
        System.out.println("nl_BE: "+StringEscapeUtils.escapeJava("Accountgeschiedenis weergeven"));
        System.out.println("de_BE: "+StringEscapeUtils.escapeJava("Kontoverlauf anzeigen"));
        System.out.println("fr_BE: "+StringEscapeUtils.escapeJava("Voir l'historique du compte"));
        // System.out.println("pl_PL: "+StringEscapeUtils.escapeJava(""));

    }
}
